In [14]:
import numpy as np    # numpy deals with arrays and matrix

In [15]:
l=[2,3,4,76,7,8,89]

### ->numpy.array(list): use to convert list to array

In [9]:
arr=np.array(l)    # to convert list to array

In [7]:
arr

array([ 2,  3,  4, 76,  7,  8, 89])

In [10]:
type(arr)     # type is 1 dimentional array

numpy.ndarray

In [13]:
np.array([[3,4],[4,7]])    # 2 dimension array 

array([[3, 4],
       [4, 7]])

In [16]:
l

[2, 3, 4, 76, 7, 8, 89]

### ->numpy.asarray(list): also use to convert list into array

In [17]:
np.asarray(l)

array([ 2,  3,  4, 76,  7,  8, 89])

In [18]:
l

[2, 3, 4, 76, 7, 8, 89]

### ->numpy.asanyarray(list): also use to convert list into array

In [19]:
np.asanyarray(l)

array([ 2,  3,  4, 76,  7,  8, 89])

### ->numpy.matrix(list): is use to convert list into matrix.<br/> 
### ->matrix is the subset(sub class/different form of array) of array.<br/>
### ->matrix is bydefault 2 dimensional

In [21]:
mat=np.matrix(l)

In [22]:
mat

matrix([[ 2,  3,  4, 76,  7,  8, 89]])

In [23]:
type(mat)

numpy.matrix

In [25]:
np.asanyarray(mat)     # it not change because matrix is also the subset of array

matrix([[ 2,  3,  4, 76,  7,  8, 89]])